services:
  backend:
    image: nishantyadav27/flask-backend:latest
    container_name: flask-backend
    ports:
      - "3000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: devops
    depends_on:
      - mysql
    networks:
      - twotier

  frontend:
    image: nishantyadav27/frontend:latest
    container_name: nginx-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - twotier

